name: mfe_users
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  commons_dependencies:
    path: ../../commons/commons_dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
